[package]
name = "year2023"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.54.0"
itertools = "0.13.0"
rust_aoc_lib = { version = "0.1.0", path = "../shared/rust_aoc_lib" }
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas"] }
